=begin
#Devdraft AI Payment & Business Management API

# A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.17.0

=end

require 'cgi'

module Devdraft
  class APIHealthApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Authenticated health check endpoint
    # @param [Hash] opts the optional parameters
    # @return [HealthResponseDto]
    def health_controller_check_v0(opts = {})
      data, _status_code, _headers = health_controller_check_v0_with_http_info(opts)
      data
    end

    # Authenticated health check endpoint
    # @param [Hash] opts the optional parameters
    # @return [Array<(HealthResponseDto, Integer, Hash)>] HealthResponseDto data, response status code and response headers
    def health_controller_check_v0_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: APIHealthApi.health_controller_check_v0 ...'
      end
      # resource path
      local_var_path = '/api/v0/health'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'HealthResponseDto'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['x-client-secret', 'x-client-key']

      new_options = opts.merge(
        :operation => :"APIHealthApi.health_controller_check_v0",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: APIHealthApi#health_controller_check_v0\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Public health check endpoint
    # @param [Hash] opts the optional parameters
    # @return [PublicHealthResponseDto]
    def health_controller_public_health_check_v0(opts = {})
      data, _status_code, _headers = health_controller_public_health_check_v0_with_http_info(opts)
      data
    end

    # Public health check endpoint
    # @param [Hash] opts the optional parameters
    # @return [Array<(PublicHealthResponseDto, Integer, Hash)>] PublicHealthResponseDto data, response status code and response headers
    def health_controller_public_health_check_v0_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: APIHealthApi.health_controller_public_health_check_v0 ...'
      end
      # resource path
      local_var_path = '/api/v0/health/public'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'PublicHealthResponseDto'

      # auth_names
      auth_names = opts[:debug_auth_names] || []

      new_options = opts.merge(
        :operation => :"APIHealthApi.health_controller_public_health_check_v0",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: APIHealthApi#health_controller_public_health_check_v0\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
