=begin
#Devdraft AI Payment & Business Management API

# A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.17.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Devdraft::InvoicesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'InvoicesApi' do
  before do
    # run before each test
    @api_instance = Devdraft::InvoicesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of InvoicesApi' do
    it 'should create an instance of InvoicesApi' do
      expect(@api_instance).to be_instance_of(Devdraft::InvoicesApi)
    end
  end

  # unit tests for invoice_controller_create
  # Create a new invoice
  # @param create_invoice_dto 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'invoice_controller_create test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for invoice_controller_find_all
  # Get all invoices
  # @param [Hash] opts the optional parameters
  # @option opts [Float] :skip Number of records to skip
  # @option opts [Float] :take Number of records to take
  # @return [nil]
  describe 'invoice_controller_find_all test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for invoice_controller_find_one
  # Get an invoice by ID
  # @param id Invoice ID
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'invoice_controller_find_one test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for invoice_controller_update
  # Update an invoice
  # @param id Invoice ID
  # @param create_invoice_dto 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'invoice_controller_update test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
