=begin
#Devdraft AI Payment & Business Management API

# A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.17.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Devdraft::PaymentLinksApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'PaymentLinksApi' do
  before do
    # run before each test
    @api_instance = Devdraft::PaymentLinksApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PaymentLinksApi' do
    it 'should create an instance of PaymentLinksApi' do
      expect(@api_instance).to be_instance_of(Devdraft::PaymentLinksApi)
    end
  end

  # unit tests for payment_links_controller_create
  # Create a new payment link
  # Creates a new payment link with the provided details. Supports both simple one-time payments and complex product bundles.
  # @param create_payment_link_dto Payment link creation data
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'payment_links_controller_create test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for payment_links_controller_find_all
  # Get all payment links
  # @param [Hash] opts the optional parameters
  # @option opts [String] :skip Number of records to skip (must be non-negative)
  # @option opts [String] :take Number of records to take (must be positive)
  # @return [nil]
  describe 'payment_links_controller_find_all test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for payment_links_controller_find_one
  # Get a payment link by ID
  # @param id Payment Link ID
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'payment_links_controller_find_one test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for payment_links_controller_update
  # Update a payment link
  # @param id Payment Link ID
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'payment_links_controller_update test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
