=begin
#Devdraft AI Payment & Business Management API

# A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.17.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Devdraft::PaymentIntentsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'PaymentIntentsApi' do
  before do
    # run before each test
    @api_instance = Devdraft::PaymentIntentsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PaymentIntentsApi' do
    it 'should create an instance of PaymentIntentsApi' do
      expect(@api_instance).to be_instance_of(Devdraft::PaymentIntentsApi)
    end
  end

  # unit tests for payment_intent_controller_create_bank_payment_intent
  # Create a bank payment intent
  # Creates a new bank payment intent for fiat-to-stablecoin transfers.      This endpoint allows you to create payment intents for bank transfers (ACH, Wire, SEPA) that convert to stablecoins. Perfect for onboarding users from traditional banking to crypto.  ## Supported Payment Rails - **ACH_PUSH**: US bank transfers (same-day or standard) - **WIRE**: International wire transfers - **SEPA**: European bank transfers  ## Use Cases - USD bank account to USDC conversion - EUR bank account to EURC conversion - MXN bank account to stablecoin conversion - Flexible amount payment intents for variable pricing  ## Supported Source Currencies - **USD**: US Dollar - **EUR**: Euro - **MXN**: Mexican Peso  ## Example: USD Bank to USDC &#x60;&#x60;&#x60;json {   \&quot;sourcePaymentRail\&quot;: \&quot;ach_push\&quot;,   \&quot;sourceCurrency\&quot;: \&quot;usd\&quot;,   \&quot;destinationCurrency\&quot;: \&quot;usdc\&quot;,   \&quot;destinationNetwork\&quot;: \&quot;ethereum\&quot;,   \&quot;destinationAddress\&quot;: \&quot;0x742d35Cc6634C0532925a3b8D4C9db96c4b4d8e1\&quot;,   \&quot;amount\&quot;: \&quot;1000.00\&quot;,   \&quot;customer_first_name\&quot;: \&quot;John\&quot;,   \&quot;customer_last_name\&quot;: \&quot;Doe\&quot;,   \&quot;customer_email\&quot;: \&quot;john.doe@example.com\&quot;,   \&quot;ach_reference\&quot;: \&quot;INV12345\&quot; } &#x60;&#x60;&#x60;  ## Reference Fields Use appropriate reference fields based on the payment rail: - &#x60;ach_reference&#x60;: For ACH transfers (max 10 chars, alphanumeric + spaces) - &#x60;wire_message&#x60;: For wire transfers (max 256 chars) - &#x60;sepa_reference&#x60;: For SEPA transfers (6-140 chars, specific character set)  ## Idempotency Include an &#x60;idempotency-key&#x60; header with a unique UUID v4 to prevent duplicate payments. Subsequent requests with the same key will return the original response.
  # @param idempotency_key Unique UUID v4 for idempotent requests. Prevents duplicate payments.
  # @param create_bank_payment_intent_dto Bank payment intent creation data
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'payment_intent_controller_create_bank_payment_intent test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for payment_intent_controller_create_stable_payment_intent
  # Create a stable payment intent
  # Creates a new stable payment intent for stablecoin-to-stablecoin transfers.      This endpoint allows you to create payment intents for transfers between different stablecoins and networks. Perfect for cross-chain stablecoin swaps and conversions.  ## Use Cases - USDC to EURC conversions - Cross-chain stablecoin transfers (e.g., Ethereum USDC to Polygon USDC) - Flexible amount payment intents for dynamic pricing  ## Example: USDC to EURC Conversion &#x60;&#x60;&#x60;json {   \&quot;sourceCurrency\&quot;: \&quot;usdc\&quot;,   \&quot;sourceNetwork\&quot;: \&quot;ethereum\&quot;,   \&quot;destinationCurrency\&quot;: \&quot;eurc\&quot;,   \&quot;destinationNetwork\&quot;: \&quot;polygon\&quot;,   \&quot;destinationAddress\&quot;: \&quot;0x742d35Cc6634C0532925a3b8D4C9db96c4b4d8e1\&quot;,   \&quot;amount\&quot;: \&quot;100.00\&quot;,   \&quot;customer_first_name\&quot;: \&quot;John\&quot;,   \&quot;customer_last_name\&quot;: \&quot;Doe\&quot;,   \&quot;customer_email\&quot;: \&quot;john.doe@example.com\&quot; } &#x60;&#x60;&#x60;  ## Flexible Amount Payments Omit the &#x60;amount&#x60; field to create a flexible payment intent where users can specify the amount during payment.  ## Idempotency Include an &#x60;idempotency-key&#x60; header with a unique UUID v4 to prevent duplicate payments. Subsequent requests with the same key will return the original response.
  # @param idempotency_key Unique UUID v4 for idempotent requests. Prevents duplicate payments.
  # @param create_stable_payment_intent_dto Stable payment intent creation data
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'payment_intent_controller_create_stable_payment_intent test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
