=begin
#Devdraft AI Payment & Business Management API

# A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.17.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Devdraft::WebhooksApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'WebhooksApi' do
  before do
    # run before each test
    @api_instance = Devdraft::WebhooksApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of WebhooksApi' do
    it 'should create an instance of WebhooksApi' do
      expect(@api_instance).to be_instance_of(Devdraft::WebhooksApi)
    end
  end

  # unit tests for webhook_controller_create
  # Create a new webhook
  # Creates a new webhook endpoint for receiving event notifications. Requires webhook:create scope.
  # @param create_webhook_dto Webhook configuration details
  # @param [Hash] opts the optional parameters
  # @return [WebhookResponseDto]
  describe 'webhook_controller_create test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for webhook_controller_find_all
  # Get all webhooks
  # Retrieves a list of all webhooks for your application. Requires webhook:read scope.
  # @param [Hash] opts the optional parameters
  # @option opts [Float] :skip Number of records to skip (default: 0)
  # @option opts [Float] :take Number of records to return (default: 10)
  # @return [Array<WebhookResponseDto>]
  describe 'webhook_controller_find_all test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for webhook_controller_find_one
  # Get a webhook by id
  # Retrieves details for a specific webhook. Requires webhook:read scope.
  # @param id Webhook unique identifier (UUID)
  # @param [Hash] opts the optional parameters
  # @return [WebhookResponseDto]
  describe 'webhook_controller_find_one test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for webhook_controller_remove
  # Delete a webhook
  # Deletes a webhook configuration. Requires webhook:delete scope.
  # @param id Webhook unique identifier (UUID)
  # @param [Hash] opts the optional parameters
  # @return [WebhookResponseDto]
  describe 'webhook_controller_remove test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for webhook_controller_update
  # Update a webhook
  # Updates an existing webhook configuration. Requires webhook:update scope.
  # @param id Webhook unique identifier (UUID)
  # @param update_webhook_dto Webhook update details
  # @param [Hash] opts the optional parameters
  # @return [WebhookResponseDto]
  describe 'webhook_controller_update test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
