=begin
#Devdraft AI Payment & Business Management API

# A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.17.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Devdraft::AggregatedBalanceResponse
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Devdraft::AggregatedBalanceResponse do
  #let(:instance) { Devdraft::AggregatedBalanceResponse.new }

  describe 'test an instance of AggregatedBalanceResponse' do
    it 'should create an instance of AggregatedBalanceResponse' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Devdraft::AggregatedBalanceResponse)
    end
  end

  describe 'test attribute "currency"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["usdc", "eurc"])
      # validator.allowable_values.each do |value|
      #   expect { instance.currency = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "total_balance"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "balances"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
