=begin
#Devdraft AI Payment & Business Management API

# A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.17.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Devdraft::BridgeFiatPaymentRail
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Devdraft::BridgeFiatPaymentRail do
  #let(:instance) { Devdraft::BridgeFiatPaymentRail.new }

  describe 'test an instance of BridgeFiatPaymentRail' do
    it 'should create an instance of BridgeFiatPaymentRail' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Devdraft::BridgeFiatPaymentRail)
    end
  end

end
