=begin
#Devdraft AI Payment & Business Management API

# A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.17.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Devdraft::ExchangeRateResponseDto
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Devdraft::ExchangeRateResponseDto do
  #let(:instance) { Devdraft::ExchangeRateResponseDto.new }

  describe 'test an instance of ExchangeRateResponseDto' do
    it 'should create an instance of ExchangeRateResponseDto' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Devdraft::ExchangeRateResponseDto)
    end
  end

  describe 'test attribute "from"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "to"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "midmarket_rate"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "buy_rate"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "sell_rate"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "timestamp"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
