=begin
#Devdraft AI Payment & Business Management API

# A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.17.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Devdraft::UpdateTaxDto
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Devdraft::UpdateTaxDto do
  #let(:instance) { Devdraft::UpdateTaxDto.new }

  describe 'test an instance of UpdateTaxDto' do
    it 'should create an instance of UpdateTaxDto' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Devdraft::UpdateTaxDto)
    end
  end

  describe 'test attribute "name"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "description"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "percentage"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "active"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "app_ids"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
