=begin
#Devdraft AI Payment & Business Management API

# A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.17.0

=end

require 'date'
require 'time'

module Devdraft
  class BridgeFiatPaymentRail
    ACH = "ach".freeze
    ACH_PUSH = "ach_push".freeze
    ACH_SAME_DAY = "ach_same_day".freeze
    WIRE = "wire".freeze
    SEPA = "sepa".freeze
    SWIFT = "swift".freeze
    SPEI = "spei".freeze

    def self.all_vars
      @all_vars ||= [ACH, ACH_PUSH, ACH_SAME_DAY, WIRE, SEPA, SWIFT, SPEI].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if BridgeFiatPaymentRail.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #BridgeFiatPaymentRail"
    end
  end
end
