=begin
#Devdraft AI Payment & Business Management API

# A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.17.0

=end

require 'date'
require 'time'

module Devdraft
  class CreatePaymentLinkDto < ApiModelBase
    # Display title for the payment link. This appears on the checkout page and in customer communications.
    attr_accessor :title

    # Unique URL slug for the payment link. Can be a full URL or just the path segment. Must be unique within your account.
    attr_accessor :url

    # Detailed description of what the customer is purchasing. Supports markdown formatting.
    attr_accessor :description

    # Cover image URL
    attr_accessor :cover_image

    # Type of the payment link
    attr_accessor :link_type

    # Amount for the payment link
    attr_accessor :amount

    # Payment for ID
    attr_accessor :payment_for_id

    # Customer ID
    attr_accessor :customer_id

    # Array of products in the payment link
    attr_accessor :payment_link_products

    # Whether the payment link is for all products
    attr_accessor :is_for_all_product

    # Whether to allow quantity adjustment
    attr_accessor :allow_quantity_adjustment

    # Whether to collect tax
    attr_accessor :collect_tax

    # Tax ID
    attr_accessor :tax_id

    # Whether to collect address
    attr_accessor :collect_address

    # Whether to limit payments
    attr_accessor :limit_payments

    # Maximum number of payments
    attr_accessor :max_payments

    # Custom fields
    attr_accessor :custom_fields

    # Whether to allow mobile payment
    attr_accessor :allow_mobile_payment

    # Currency
    attr_accessor :currency

    # Expiration date
    attr_accessor :expiration_date

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'title' => :'title',
        :'url' => :'url',
        :'description' => :'description',
        :'cover_image' => :'coverImage',
        :'link_type' => :'linkType',
        :'amount' => :'amount',
        :'payment_for_id' => :'paymentForId',
        :'customer_id' => :'customerId',
        :'payment_link_products' => :'paymentLinkProducts',
        :'is_for_all_product' => :'isForAllProduct',
        :'allow_quantity_adjustment' => :'allowQuantityAdjustment',
        :'collect_tax' => :'collectTax',
        :'tax_id' => :'taxId',
        :'collect_address' => :'collectAddress',
        :'limit_payments' => :'limitPayments',
        :'max_payments' => :'maxPayments',
        :'custom_fields' => :'customFields',
        :'allow_mobile_payment' => :'allowMobilePayment',
        :'currency' => :'currency',
        :'expiration_date' => :'expiration_date'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'title' => :'String',
        :'url' => :'String',
        :'description' => :'String',
        :'cover_image' => :'String',
        :'link_type' => :'String',
        :'amount' => :'Float',
        :'payment_for_id' => :'String',
        :'customer_id' => :'String',
        :'payment_link_products' => :'Array<PaymentLinkProductDto>',
        :'is_for_all_product' => :'Boolean',
        :'allow_quantity_adjustment' => :'Boolean',
        :'collect_tax' => :'Boolean',
        :'tax_id' => :'String',
        :'collect_address' => :'Boolean',
        :'limit_payments' => :'Boolean',
        :'max_payments' => :'Float',
        :'custom_fields' => :'Object',
        :'allow_mobile_payment' => :'Boolean',
        :'currency' => :'String',
        :'expiration_date' => :'Time'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Devdraft::CreatePaymentLinkDto` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Devdraft::CreatePaymentLinkDto`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'title')
        self.title = attributes[:'title']
      else
        self.title = nil
      end

      if attributes.key?(:'url')
        self.url = attributes[:'url']
      else
        self.url = nil
      end

      if attributes.key?(:'description')
        self.description = attributes[:'description']
      end

      if attributes.key?(:'cover_image')
        self.cover_image = attributes[:'cover_image']
      end

      if attributes.key?(:'link_type')
        self.link_type = attributes[:'link_type']
      else
        self.link_type = nil
      end

      if attributes.key?(:'amount')
        self.amount = attributes[:'amount']
      end

      if attributes.key?(:'payment_for_id')
        self.payment_for_id = attributes[:'payment_for_id']
      end

      if attributes.key?(:'customer_id')
        self.customer_id = attributes[:'customer_id']
      end

      if attributes.key?(:'payment_link_products')
        if (value = attributes[:'payment_link_products']).is_a?(Array)
          self.payment_link_products = value
        end
      end

      if attributes.key?(:'is_for_all_product')
        self.is_for_all_product = attributes[:'is_for_all_product']
      else
        self.is_for_all_product = false
      end

      if attributes.key?(:'allow_quantity_adjustment')
        self.allow_quantity_adjustment = attributes[:'allow_quantity_adjustment']
      else
        self.allow_quantity_adjustment = true
      end

      if attributes.key?(:'collect_tax')
        self.collect_tax = attributes[:'collect_tax']
      else
        self.collect_tax = false
      end

      if attributes.key?(:'tax_id')
        self.tax_id = attributes[:'tax_id']
      end

      if attributes.key?(:'collect_address')
        self.collect_address = attributes[:'collect_address']
      else
        self.collect_address = false
      end

      if attributes.key?(:'limit_payments')
        self.limit_payments = attributes[:'limit_payments']
      else
        self.limit_payments = false
      end

      if attributes.key?(:'max_payments')
        self.max_payments = attributes[:'max_payments']
      end

      if attributes.key?(:'custom_fields')
        self.custom_fields = attributes[:'custom_fields']
      end

      if attributes.key?(:'allow_mobile_payment')
        self.allow_mobile_payment = attributes[:'allow_mobile_payment']
      else
        self.allow_mobile_payment = false
      end

      if attributes.key?(:'currency')
        self.currency = attributes[:'currency']
      else
        self.currency = 'usdc'
      end

      if attributes.key?(:'expiration_date')
        self.expiration_date = attributes[:'expiration_date']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @title.nil?
        invalid_properties.push('invalid value for "title", title cannot be nil.')
      end

      if @title.to_s.length > 100
        invalid_properties.push('invalid value for "title", the character length must be smaller than or equal to 100.')
      end

      if @title.to_s.length < 3
        invalid_properties.push('invalid value for "title", the character length must be greater than or equal to 3.')
      end

      if @url.nil?
        invalid_properties.push('invalid value for "url", url cannot be nil.')
      end

      if !@description.nil? && @description.to_s.length > 500
        invalid_properties.push('invalid value for "description", the character length must be smaller than or equal to 500.')
      end

      if @link_type.nil?
        invalid_properties.push('invalid value for "link_type", link_type cannot be nil.')
      end

      if !@amount.nil? && @amount < 0.01
        invalid_properties.push('invalid value for "amount", must be greater than or equal to 0.01.')
      end

      if @allow_quantity_adjustment.nil?
        invalid_properties.push('invalid value for "allow_quantity_adjustment", allow_quantity_adjustment cannot be nil.')
      end

      if @collect_tax.nil?
        invalid_properties.push('invalid value for "collect_tax", collect_tax cannot be nil.')
      end

      if @collect_address.nil?
        invalid_properties.push('invalid value for "collect_address", collect_address cannot be nil.')
      end

      if !@max_payments.nil? && @max_payments < 1
        invalid_properties.push('invalid value for "max_payments", must be greater than or equal to 1.')
      end

      if @allow_mobile_payment.nil?
        invalid_properties.push('invalid value for "allow_mobile_payment", allow_mobile_payment cannot be nil.')
      end

      if @currency.nil?
        invalid_properties.push('invalid value for "currency", currency cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @title.nil?
      return false if @title.to_s.length > 100
      return false if @title.to_s.length < 3
      return false if @url.nil?
      return false if !@description.nil? && @description.to_s.length > 500
      return false if @link_type.nil?
      link_type_validator = EnumAttributeValidator.new('String', ["INVOICE", "PRODUCT", "COLLECTION", "DONATION"])
      return false unless link_type_validator.valid?(@link_type)
      return false if !@amount.nil? && @amount < 0.01
      return false if @allow_quantity_adjustment.nil?
      return false if @collect_tax.nil?
      return false if @collect_address.nil?
      return false if !@max_payments.nil? && @max_payments < 1
      return false if @allow_mobile_payment.nil?
      return false if @currency.nil?
      currency_validator = EnumAttributeValidator.new('String', ["usdc", "eurc"])
      return false unless currency_validator.valid?(@currency)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] title Value to be assigned
    def title=(title)
      if title.nil?
        fail ArgumentError, 'title cannot be nil'
      end

      if title.to_s.length > 100
        fail ArgumentError, 'invalid value for "title", the character length must be smaller than or equal to 100.'
      end

      if title.to_s.length < 3
        fail ArgumentError, 'invalid value for "title", the character length must be greater than or equal to 3.'
      end

      @title = title
    end

    # Custom attribute writer method with validation
    # @param [Object] url Value to be assigned
    def url=(url)
      if url.nil?
        fail ArgumentError, 'url cannot be nil'
      end

      @url = url
    end

    # Custom attribute writer method with validation
    # @param [Object] description Value to be assigned
    def description=(description)
      if description.nil?
        fail ArgumentError, 'description cannot be nil'
      end

      if description.to_s.length > 500
        fail ArgumentError, 'invalid value for "description", the character length must be smaller than or equal to 500.'
      end

      @description = description
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] link_type Object to be assigned
    def link_type=(link_type)
      validator = EnumAttributeValidator.new('String', ["INVOICE", "PRODUCT", "COLLECTION", "DONATION"])
      unless validator.valid?(link_type)
        fail ArgumentError, "invalid value for \"link_type\", must be one of #{validator.allowable_values}."
      end
      @link_type = link_type
    end

    # Custom attribute writer method with validation
    # @param [Object] amount Value to be assigned
    def amount=(amount)
      if amount.nil?
        fail ArgumentError, 'amount cannot be nil'
      end

      if amount < 0.01
        fail ArgumentError, 'invalid value for "amount", must be greater than or equal to 0.01.'
      end

      @amount = amount
    end

    # Custom attribute writer method with validation
    # @param [Object] allow_quantity_adjustment Value to be assigned
    def allow_quantity_adjustment=(allow_quantity_adjustment)
      if allow_quantity_adjustment.nil?
        fail ArgumentError, 'allow_quantity_adjustment cannot be nil'
      end

      @allow_quantity_adjustment = allow_quantity_adjustment
    end

    # Custom attribute writer method with validation
    # @param [Object] collect_tax Value to be assigned
    def collect_tax=(collect_tax)
      if collect_tax.nil?
        fail ArgumentError, 'collect_tax cannot be nil'
      end

      @collect_tax = collect_tax
    end

    # Custom attribute writer method with validation
    # @param [Object] collect_address Value to be assigned
    def collect_address=(collect_address)
      if collect_address.nil?
        fail ArgumentError, 'collect_address cannot be nil'
      end

      @collect_address = collect_address
    end

    # Custom attribute writer method with validation
    # @param [Object] max_payments Value to be assigned
    def max_payments=(max_payments)
      if max_payments.nil?
        fail ArgumentError, 'max_payments cannot be nil'
      end

      if max_payments < 1
        fail ArgumentError, 'invalid value for "max_payments", must be greater than or equal to 1.'
      end

      @max_payments = max_payments
    end

    # Custom attribute writer method with validation
    # @param [Object] allow_mobile_payment Value to be assigned
    def allow_mobile_payment=(allow_mobile_payment)
      if allow_mobile_payment.nil?
        fail ArgumentError, 'allow_mobile_payment cannot be nil'
      end

      @allow_mobile_payment = allow_mobile_payment
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] currency Object to be assigned
    def currency=(currency)
      validator = EnumAttributeValidator.new('String', ["usdc", "eurc"])
      unless validator.valid?(currency)
        fail ArgumentError, "invalid value for \"currency\", must be one of #{validator.allowable_values}."
      end
      @currency = currency
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          title == o.title &&
          url == o.url &&
          description == o.description &&
          cover_image == o.cover_image &&
          link_type == o.link_type &&
          amount == o.amount &&
          payment_for_id == o.payment_for_id &&
          customer_id == o.customer_id &&
          payment_link_products == o.payment_link_products &&
          is_for_all_product == o.is_for_all_product &&
          allow_quantity_adjustment == o.allow_quantity_adjustment &&
          collect_tax == o.collect_tax &&
          tax_id == o.tax_id &&
          collect_address == o.collect_address &&
          limit_payments == o.limit_payments &&
          max_payments == o.max_payments &&
          custom_fields == o.custom_fields &&
          allow_mobile_payment == o.allow_mobile_payment &&
          currency == o.currency &&
          expiration_date == o.expiration_date
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [title, url, description, cover_image, link_type, amount, payment_for_id, customer_id, payment_link_products, is_for_all_product, allow_quantity_adjustment, collect_tax, tax_id, collect_address, limit_payments, max_payments, custom_fields, allow_mobile_payment, currency, expiration_date].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
