=begin
#Devdraft AI Payment & Business Management API

# A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.17.0

=end

require 'date'
require 'time'

module Devdraft
  class CreateInvoiceDto < ApiModelBase
    # Name of the invoice
    attr_accessor :name

    # Email address
    attr_accessor :email

    # Customer ID
    attr_accessor :customer_id

    # Currency for the invoice
    attr_accessor :currency

    attr_accessor :items

    # Due date of the invoice
    attr_accessor :due_date

    # Delivery method
    attr_accessor :delivery

    # Whether to generate a payment link
    attr_accessor :payment_link

    # Array of accepted payment methods
    attr_accessor :payment_methods

    # Invoice status
    attr_accessor :status

    # Address
    attr_accessor :address

    # Phone number
    attr_accessor :phone_number

    # Send date
    attr_accessor :send_date

    # Logo URL
    attr_accessor :logo

    # Allow partial payments
    attr_accessor :partial_payment

    # Tax ID
    attr_accessor :tax_id

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'name' => :'name',
        :'email' => :'email',
        :'customer_id' => :'customer_id',
        :'currency' => :'currency',
        :'items' => :'items',
        :'due_date' => :'due_date',
        :'delivery' => :'delivery',
        :'payment_link' => :'payment_link',
        :'payment_methods' => :'payment_methods',
        :'status' => :'status',
        :'address' => :'address',
        :'phone_number' => :'phone_number',
        :'send_date' => :'send_date',
        :'logo' => :'logo',
        :'partial_payment' => :'partial_payment',
        :'tax_id' => :'taxId'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'name' => :'String',
        :'email' => :'String',
        :'customer_id' => :'String',
        :'currency' => :'String',
        :'items' => :'Object',
        :'due_date' => :'Time',
        :'delivery' => :'String',
        :'payment_link' => :'Boolean',
        :'payment_methods' => :'Array<String>',
        :'status' => :'String',
        :'address' => :'String',
        :'phone_number' => :'String',
        :'send_date' => :'Time',
        :'logo' => :'String',
        :'partial_payment' => :'Boolean',
        :'tax_id' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Devdraft::CreateInvoiceDto` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Devdraft::CreateInvoiceDto`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      else
        self.name = nil
      end

      if attributes.key?(:'email')
        self.email = attributes[:'email']
      else
        self.email = nil
      end

      if attributes.key?(:'customer_id')
        self.customer_id = attributes[:'customer_id']
      else
        self.customer_id = nil
      end

      if attributes.key?(:'currency')
        self.currency = attributes[:'currency']
      else
        self.currency = nil
      end

      if attributes.key?(:'items')
        self.items = attributes[:'items']
      else
        self.items = nil
      end

      if attributes.key?(:'due_date')
        self.due_date = attributes[:'due_date']
      else
        self.due_date = nil
      end

      if attributes.key?(:'delivery')
        self.delivery = attributes[:'delivery']
      else
        self.delivery = nil
      end

      if attributes.key?(:'payment_link')
        self.payment_link = attributes[:'payment_link']
      else
        self.payment_link = nil
      end

      if attributes.key?(:'payment_methods')
        if (value = attributes[:'payment_methods']).is_a?(Array)
          self.payment_methods = value
        end
      else
        self.payment_methods = nil
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      else
        self.status = nil
      end

      if attributes.key?(:'address')
        self.address = attributes[:'address']
      end

      if attributes.key?(:'phone_number')
        self.phone_number = attributes[:'phone_number']
      end

      if attributes.key?(:'send_date')
        self.send_date = attributes[:'send_date']
      end

      if attributes.key?(:'logo')
        self.logo = attributes[:'logo']
      end

      if attributes.key?(:'partial_payment')
        self.partial_payment = attributes[:'partial_payment']
      else
        self.partial_payment = nil
      end

      if attributes.key?(:'tax_id')
        self.tax_id = attributes[:'tax_id']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @name.nil?
        invalid_properties.push('invalid value for "name", name cannot be nil.')
      end

      if @email.nil?
        invalid_properties.push('invalid value for "email", email cannot be nil.')
      end

      if @customer_id.nil?
        invalid_properties.push('invalid value for "customer_id", customer_id cannot be nil.')
      end

      if @currency.nil?
        invalid_properties.push('invalid value for "currency", currency cannot be nil.')
      end

      if @items.nil?
        invalid_properties.push('invalid value for "items", items cannot be nil.')
      end

      if @due_date.nil?
        invalid_properties.push('invalid value for "due_date", due_date cannot be nil.')
      end

      if @delivery.nil?
        invalid_properties.push('invalid value for "delivery", delivery cannot be nil.')
      end

      if @payment_link.nil?
        invalid_properties.push('invalid value for "payment_link", payment_link cannot be nil.')
      end

      if @payment_methods.nil?
        invalid_properties.push('invalid value for "payment_methods", payment_methods cannot be nil.')
      end

      if @status.nil?
        invalid_properties.push('invalid value for "status", status cannot be nil.')
      end

      if @partial_payment.nil?
        invalid_properties.push('invalid value for "partial_payment", partial_payment cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @name.nil?
      return false if @email.nil?
      return false if @customer_id.nil?
      return false if @currency.nil?
      currency_validator = EnumAttributeValidator.new('String', ["usdc", "eurc"])
      return false unless currency_validator.valid?(@currency)
      return false if @items.nil?
      return false if @due_date.nil?
      return false if @delivery.nil?
      delivery_validator = EnumAttributeValidator.new('String', ["EMAIL", "MANUALLY"])
      return false unless delivery_validator.valid?(@delivery)
      return false if @payment_link.nil?
      return false if @payment_methods.nil?
      return false if @status.nil?
      status_validator = EnumAttributeValidator.new('String', ["DRAFT", "OPEN", "PASTDUE", "PAID", "PARTIALLYPAID"])
      return false unless status_validator.valid?(@status)
      return false if @partial_payment.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] name Value to be assigned
    def name=(name)
      if name.nil?
        fail ArgumentError, 'name cannot be nil'
      end

      @name = name
    end

    # Custom attribute writer method with validation
    # @param [Object] email Value to be assigned
    def email=(email)
      if email.nil?
        fail ArgumentError, 'email cannot be nil'
      end

      @email = email
    end

    # Custom attribute writer method with validation
    # @param [Object] customer_id Value to be assigned
    def customer_id=(customer_id)
      if customer_id.nil?
        fail ArgumentError, 'customer_id cannot be nil'
      end

      @customer_id = customer_id
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] currency Object to be assigned
    def currency=(currency)
      validator = EnumAttributeValidator.new('String', ["usdc", "eurc"])
      unless validator.valid?(currency)
        fail ArgumentError, "invalid value for \"currency\", must be one of #{validator.allowable_values}."
      end
      @currency = currency
    end

    # Custom attribute writer method with validation
    # @param [Object] items Value to be assigned
    def items=(items)
      if items.nil?
        fail ArgumentError, 'items cannot be nil'
      end

      @items = items
    end

    # Custom attribute writer method with validation
    # @param [Object] due_date Value to be assigned
    def due_date=(due_date)
      if due_date.nil?
        fail ArgumentError, 'due_date cannot be nil'
      end

      @due_date = due_date
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] delivery Object to be assigned
    def delivery=(delivery)
      validator = EnumAttributeValidator.new('String', ["EMAIL", "MANUALLY"])
      unless validator.valid?(delivery)
        fail ArgumentError, "invalid value for \"delivery\", must be one of #{validator.allowable_values}."
      end
      @delivery = delivery
    end

    # Custom attribute writer method with validation
    # @param [Object] payment_link Value to be assigned
    def payment_link=(payment_link)
      if payment_link.nil?
        fail ArgumentError, 'payment_link cannot be nil'
      end

      @payment_link = payment_link
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] status Object to be assigned
    def status=(status)
      validator = EnumAttributeValidator.new('String', ["DRAFT", "OPEN", "PASTDUE", "PAID", "PARTIALLYPAID"])
      unless validator.valid?(status)
        fail ArgumentError, "invalid value for \"status\", must be one of #{validator.allowable_values}."
      end
      @status = status
    end

    # Custom attribute writer method with validation
    # @param [Object] partial_payment Value to be assigned
    def partial_payment=(partial_payment)
      if partial_payment.nil?
        fail ArgumentError, 'partial_payment cannot be nil'
      end

      @partial_payment = partial_payment
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          name == o.name &&
          email == o.email &&
          customer_id == o.customer_id &&
          currency == o.currency &&
          items == o.items &&
          due_date == o.due_date &&
          delivery == o.delivery &&
          payment_link == o.payment_link &&
          payment_methods == o.payment_methods &&
          status == o.status &&
          address == o.address &&
          phone_number == o.phone_number &&
          send_date == o.send_date &&
          logo == o.logo &&
          partial_payment == o.partial_payment &&
          tax_id == o.tax_id
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [name, email, customer_id, currency, items, due_date, delivery, payment_link, payment_methods, status, address, phone_number, send_date, logo, partial_payment, tax_id].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
