=begin
#Devdraft AI Payment & Business Management API

# A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.17.0

=end

require 'date'
require 'time'

module Devdraft
  class CreateLiquidationAddressDto < ApiModelBase
    # The blockchain chain for the liquidation address
    attr_accessor :chain

    # The currency for the liquidation address
    attr_accessor :currency

    # The liquidation address on the blockchain
    attr_accessor :address

    # External bank account to send funds to
    attr_accessor :external_account_id

    # Developer's prefunded account id
    attr_accessor :prefunded_account_id

    # Bridge Wallet to send funds to
    attr_accessor :bridge_wallet_id

    # Payment rail for sending funds
    attr_accessor :destination_payment_rail

    # Currency for sending funds
    attr_accessor :destination_currency

    # Message for wire transfers
    attr_accessor :destination_wire_message

    # Reference for SEPA transactions
    attr_accessor :destination_sepa_reference

    # Reference for ACH transactions
    attr_accessor :destination_ach_reference

    # Crypto wallet address for crypto transfers
    attr_accessor :destination_address

    # Memo for blockchain transactions
    attr_accessor :destination_blockchain_memo

    # Address to return funds on failed transactions (Not supported on Stellar)
    attr_accessor :return_address

    # Custom developer fee percentage (Base 100 percentage: 10.2% = \"10.2\")
    attr_accessor :custom_developer_fee_percent

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'chain' => :'chain',
        :'currency' => :'currency',
        :'address' => :'address',
        :'external_account_id' => :'external_account_id',
        :'prefunded_account_id' => :'prefunded_account_id',
        :'bridge_wallet_id' => :'bridge_wallet_id',
        :'destination_payment_rail' => :'destination_payment_rail',
        :'destination_currency' => :'destination_currency',
        :'destination_wire_message' => :'destination_wire_message',
        :'destination_sepa_reference' => :'destination_sepa_reference',
        :'destination_ach_reference' => :'destination_ach_reference',
        :'destination_address' => :'destination_address',
        :'destination_blockchain_memo' => :'destination_blockchain_memo',
        :'return_address' => :'return_address',
        :'custom_developer_fee_percent' => :'custom_developer_fee_percent'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'chain' => :'String',
        :'currency' => :'String',
        :'address' => :'String',
        :'external_account_id' => :'String',
        :'prefunded_account_id' => :'String',
        :'bridge_wallet_id' => :'String',
        :'destination_payment_rail' => :'BridgePaymentRail',
        :'destination_currency' => :'DestinationCurrency',
        :'destination_wire_message' => :'String',
        :'destination_sepa_reference' => :'String',
        :'destination_ach_reference' => :'String',
        :'destination_address' => :'String',
        :'destination_blockchain_memo' => :'String',
        :'return_address' => :'String',
        :'custom_developer_fee_percent' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Devdraft::CreateLiquidationAddressDto` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Devdraft::CreateLiquidationAddressDto`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'chain')
        self.chain = attributes[:'chain']
      else
        self.chain = nil
      end

      if attributes.key?(:'currency')
        self.currency = attributes[:'currency']
      else
        self.currency = nil
      end

      if attributes.key?(:'address')
        self.address = attributes[:'address']
      else
        self.address = nil
      end

      if attributes.key?(:'external_account_id')
        self.external_account_id = attributes[:'external_account_id']
      end

      if attributes.key?(:'prefunded_account_id')
        self.prefunded_account_id = attributes[:'prefunded_account_id']
      end

      if attributes.key?(:'bridge_wallet_id')
        self.bridge_wallet_id = attributes[:'bridge_wallet_id']
      end

      if attributes.key?(:'destination_payment_rail')
        self.destination_payment_rail = attributes[:'destination_payment_rail']
      end

      if attributes.key?(:'destination_currency')
        self.destination_currency = attributes[:'destination_currency']
      end

      if attributes.key?(:'destination_wire_message')
        self.destination_wire_message = attributes[:'destination_wire_message']
      end

      if attributes.key?(:'destination_sepa_reference')
        self.destination_sepa_reference = attributes[:'destination_sepa_reference']
      end

      if attributes.key?(:'destination_ach_reference')
        self.destination_ach_reference = attributes[:'destination_ach_reference']
      end

      if attributes.key?(:'destination_address')
        self.destination_address = attributes[:'destination_address']
      end

      if attributes.key?(:'destination_blockchain_memo')
        self.destination_blockchain_memo = attributes[:'destination_blockchain_memo']
      end

      if attributes.key?(:'return_address')
        self.return_address = attributes[:'return_address']
      end

      if attributes.key?(:'custom_developer_fee_percent')
        self.custom_developer_fee_percent = attributes[:'custom_developer_fee_percent']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @chain.nil?
        invalid_properties.push('invalid value for "chain", chain cannot be nil.')
      end

      if @currency.nil?
        invalid_properties.push('invalid value for "currency", currency cannot be nil.')
      end

      if @address.nil?
        invalid_properties.push('invalid value for "address", address cannot be nil.')
      end

      if !@external_account_id.nil? && @external_account_id.to_s.length > 42
        invalid_properties.push('invalid value for "external_account_id", the character length must be smaller than or equal to 42.')
      end

      if !@prefunded_account_id.nil? && @prefunded_account_id.to_s.length > 42
        invalid_properties.push('invalid value for "prefunded_account_id", the character length must be smaller than or equal to 42.')
      end

      if !@bridge_wallet_id.nil? && @bridge_wallet_id.to_s.length > 42
        invalid_properties.push('invalid value for "bridge_wallet_id", the character length must be smaller than or equal to 42.')
      end

      if !@destination_wire_message.nil? && @destination_wire_message.to_s.length > 256
        invalid_properties.push('invalid value for "destination_wire_message", the character length must be smaller than or equal to 256.')
      end

      if !@destination_sepa_reference.nil? && @destination_sepa_reference.to_s.length > 140
        invalid_properties.push('invalid value for "destination_sepa_reference", the character length must be smaller than or equal to 140.')
      end

      if !@destination_sepa_reference.nil? && @destination_sepa_reference.to_s.length < 6
        invalid_properties.push('invalid value for "destination_sepa_reference", the character length must be greater than or equal to 6.')
      end

      if !@destination_ach_reference.nil? && @destination_ach_reference.to_s.length > 10
        invalid_properties.push('invalid value for "destination_ach_reference", the character length must be smaller than or equal to 10.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @chain.nil?
      chain_validator = EnumAttributeValidator.new('String', ["ethereum", "solana", "polygon", "avalanche_c_chain", "base", "arbitrum", "optimism", "stellar", "tron"])
      return false unless chain_validator.valid?(@chain)
      return false if @currency.nil?
      currency_validator = EnumAttributeValidator.new('String', ["usdc", "eurc", "dai", "pyusd", "usdt"])
      return false unless currency_validator.valid?(@currency)
      return false if @address.nil?
      return false if !@external_account_id.nil? && @external_account_id.to_s.length > 42
      return false if !@prefunded_account_id.nil? && @prefunded_account_id.to_s.length > 42
      return false if !@bridge_wallet_id.nil? && @bridge_wallet_id.to_s.length > 42
      return false if !@destination_wire_message.nil? && @destination_wire_message.to_s.length > 256
      return false if !@destination_sepa_reference.nil? && @destination_sepa_reference.to_s.length > 140
      return false if !@destination_sepa_reference.nil? && @destination_sepa_reference.to_s.length < 6
      return false if !@destination_ach_reference.nil? && @destination_ach_reference.to_s.length > 10
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] chain Object to be assigned
    def chain=(chain)
      validator = EnumAttributeValidator.new('String', ["ethereum", "solana", "polygon", "avalanche_c_chain", "base", "arbitrum", "optimism", "stellar", "tron"])
      unless validator.valid?(chain)
        fail ArgumentError, "invalid value for \"chain\", must be one of #{validator.allowable_values}."
      end
      @chain = chain
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] currency Object to be assigned
    def currency=(currency)
      validator = EnumAttributeValidator.new('String', ["usdc", "eurc", "dai", "pyusd", "usdt"])
      unless validator.valid?(currency)
        fail ArgumentError, "invalid value for \"currency\", must be one of #{validator.allowable_values}."
      end
      @currency = currency
    end

    # Custom attribute writer method with validation
    # @param [Object] address Value to be assigned
    def address=(address)
      if address.nil?
        fail ArgumentError, 'address cannot be nil'
      end

      @address = address
    end

    # Custom attribute writer method with validation
    # @param [Object] external_account_id Value to be assigned
    def external_account_id=(external_account_id)
      if external_account_id.nil?
        fail ArgumentError, 'external_account_id cannot be nil'
      end

      if external_account_id.to_s.length > 42
        fail ArgumentError, 'invalid value for "external_account_id", the character length must be smaller than or equal to 42.'
      end

      @external_account_id = external_account_id
    end

    # Custom attribute writer method with validation
    # @param [Object] prefunded_account_id Value to be assigned
    def prefunded_account_id=(prefunded_account_id)
      if prefunded_account_id.nil?
        fail ArgumentError, 'prefunded_account_id cannot be nil'
      end

      if prefunded_account_id.to_s.length > 42
        fail ArgumentError, 'invalid value for "prefunded_account_id", the character length must be smaller than or equal to 42.'
      end

      @prefunded_account_id = prefunded_account_id
    end

    # Custom attribute writer method with validation
    # @param [Object] bridge_wallet_id Value to be assigned
    def bridge_wallet_id=(bridge_wallet_id)
      if bridge_wallet_id.nil?
        fail ArgumentError, 'bridge_wallet_id cannot be nil'
      end

      if bridge_wallet_id.to_s.length > 42
        fail ArgumentError, 'invalid value for "bridge_wallet_id", the character length must be smaller than or equal to 42.'
      end

      @bridge_wallet_id = bridge_wallet_id
    end

    # Custom attribute writer method with validation
    # @param [Object] destination_wire_message Value to be assigned
    def destination_wire_message=(destination_wire_message)
      if destination_wire_message.nil?
        fail ArgumentError, 'destination_wire_message cannot be nil'
      end

      if destination_wire_message.to_s.length > 256
        fail ArgumentError, 'invalid value for "destination_wire_message", the character length must be smaller than or equal to 256.'
      end

      @destination_wire_message = destination_wire_message
    end

    # Custom attribute writer method with validation
    # @param [Object] destination_sepa_reference Value to be assigned
    def destination_sepa_reference=(destination_sepa_reference)
      if destination_sepa_reference.nil?
        fail ArgumentError, 'destination_sepa_reference cannot be nil'
      end

      if destination_sepa_reference.to_s.length > 140
        fail ArgumentError, 'invalid value for "destination_sepa_reference", the character length must be smaller than or equal to 140.'
      end

      if destination_sepa_reference.to_s.length < 6
        fail ArgumentError, 'invalid value for "destination_sepa_reference", the character length must be greater than or equal to 6.'
      end

      @destination_sepa_reference = destination_sepa_reference
    end

    # Custom attribute writer method with validation
    # @param [Object] destination_ach_reference Value to be assigned
    def destination_ach_reference=(destination_ach_reference)
      if destination_ach_reference.nil?
        fail ArgumentError, 'destination_ach_reference cannot be nil'
      end

      if destination_ach_reference.to_s.length > 10
        fail ArgumentError, 'invalid value for "destination_ach_reference", the character length must be smaller than or equal to 10.'
      end

      @destination_ach_reference = destination_ach_reference
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          chain == o.chain &&
          currency == o.currency &&
          address == o.address &&
          external_account_id == o.external_account_id &&
          prefunded_account_id == o.prefunded_account_id &&
          bridge_wallet_id == o.bridge_wallet_id &&
          destination_payment_rail == o.destination_payment_rail &&
          destination_currency == o.destination_currency &&
          destination_wire_message == o.destination_wire_message &&
          destination_sepa_reference == o.destination_sepa_reference &&
          destination_ach_reference == o.destination_ach_reference &&
          destination_address == o.destination_address &&
          destination_blockchain_memo == o.destination_blockchain_memo &&
          return_address == o.return_address &&
          custom_developer_fee_percent == o.custom_developer_fee_percent
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [chain, currency, address, external_account_id, prefunded_account_id, bridge_wallet_id, destination_payment_rail, destination_currency, destination_wire_message, destination_sepa_reference, destination_ach_reference, destination_address, destination_blockchain_memo, return_address, custom_developer_fee_percent].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
