=begin
#Devdraft AI Payment & Business Management API

# A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.17.0

=end

require 'date'
require 'time'

module Devdraft
  class CreateExternalStablecoinTransferDto < ApiModelBase
    # The ID of the source bridge wallet
    attr_accessor :source_wallet_id

    # The source currency
    attr_accessor :source_currency

    # The destination currency
    attr_accessor :destination_currency

    # Blockchain memo for the transfer
    attr_accessor :blockchain_memo

    # Beneficiary ID for the stablecoin transfer
    attr_accessor :beneficiary_id

    # The amount to transfer
    attr_accessor :amount

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'source_wallet_id' => :'sourceWalletId',
        :'source_currency' => :'sourceCurrency',
        :'destination_currency' => :'destinationCurrency',
        :'blockchain_memo' => :'blockchain_memo',
        :'beneficiary_id' => :'beneficiaryId',
        :'amount' => :'amount'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'source_wallet_id' => :'String',
        :'source_currency' => :'String',
        :'destination_currency' => :'String',
        :'blockchain_memo' => :'String',
        :'beneficiary_id' => :'String',
        :'amount' => :'Float'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Devdraft::CreateExternalStablecoinTransferDto` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Devdraft::CreateExternalStablecoinTransferDto`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'source_wallet_id')
        self.source_wallet_id = attributes[:'source_wallet_id']
      else
        self.source_wallet_id = nil
      end

      if attributes.key?(:'source_currency')
        self.source_currency = attributes[:'source_currency']
      else
        self.source_currency = nil
      end

      if attributes.key?(:'destination_currency')
        self.destination_currency = attributes[:'destination_currency']
      else
        self.destination_currency = nil
      end

      if attributes.key?(:'blockchain_memo')
        self.blockchain_memo = attributes[:'blockchain_memo']
      end

      if attributes.key?(:'beneficiary_id')
        self.beneficiary_id = attributes[:'beneficiary_id']
      else
        self.beneficiary_id = nil
      end

      if attributes.key?(:'amount')
        self.amount = attributes[:'amount']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @source_wallet_id.nil?
        invalid_properties.push('invalid value for "source_wallet_id", source_wallet_id cannot be nil.')
      end

      if @source_currency.nil?
        invalid_properties.push('invalid value for "source_currency", source_currency cannot be nil.')
      end

      if @destination_currency.nil?
        invalid_properties.push('invalid value for "destination_currency", destination_currency cannot be nil.')
      end

      if @beneficiary_id.nil?
        invalid_properties.push('invalid value for "beneficiary_id", beneficiary_id cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @source_wallet_id.nil?
      return false if @source_currency.nil?
      return false if @destination_currency.nil?
      return false if @beneficiary_id.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] source_wallet_id Value to be assigned
    def source_wallet_id=(source_wallet_id)
      if source_wallet_id.nil?
        fail ArgumentError, 'source_wallet_id cannot be nil'
      end

      @source_wallet_id = source_wallet_id
    end

    # Custom attribute writer method with validation
    # @param [Object] source_currency Value to be assigned
    def source_currency=(source_currency)
      if source_currency.nil?
        fail ArgumentError, 'source_currency cannot be nil'
      end

      @source_currency = source_currency
    end

    # Custom attribute writer method with validation
    # @param [Object] destination_currency Value to be assigned
    def destination_currency=(destination_currency)
      if destination_currency.nil?
        fail ArgumentError, 'destination_currency cannot be nil'
      end

      @destination_currency = destination_currency
    end

    # Custom attribute writer method with validation
    # @param [Object] beneficiary_id Value to be assigned
    def beneficiary_id=(beneficiary_id)
      if beneficiary_id.nil?
        fail ArgumentError, 'beneficiary_id cannot be nil'
      end

      @beneficiary_id = beneficiary_id
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          source_wallet_id == o.source_wallet_id &&
          source_currency == o.source_currency &&
          destination_currency == o.destination_currency &&
          blockchain_memo == o.blockchain_memo &&
          beneficiary_id == o.beneficiary_id &&
          amount == o.amount
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [source_wallet_id, source_currency, destination_currency, blockchain_memo, beneficiary_id, amount].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
