=begin
#Devdraft AI Payment & Business Management API

# A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.17.0

=end

require 'date'
require 'time'

module Devdraft
  class CreateStablePaymentIntentDto < ApiModelBase
    # The stablecoin currency to convert FROM. This is the currency the customer will pay with.
    attr_accessor :source_currency

    # The blockchain network where the source currency resides. Determines gas fees and transaction speed.
    attr_accessor :source_network

    # The stablecoin currency to convert TO. If omitted, defaults to the same as source currency (cross-chain transfer).
    attr_accessor :destination_currency

    # The blockchain network where the converted currency will be delivered. Must support the destination currency.
    attr_accessor :destination_network

    # The wallet address where converted funds will be sent. Supports Ethereum (0x...) and Solana address formats.
    attr_accessor :destination_address

    # Payment amount in the source currency. Omit for flexible amount payments where users specify the amount during checkout.
    attr_accessor :amount

    # Customer's first name. Used for transaction records and compliance. Required for amounts over $1000.
    attr_accessor :customer_first_name

    # Customer's last name. Used for transaction records and compliance. Required for amounts over $1000.
    attr_accessor :customer_last_name

    # Customer's email address. Used for transaction notifications and receipts. Highly recommended for all transactions.
    attr_accessor :customer_email

    # Customer's full address. Required for compliance in certain jurisdictions and high-value transactions.
    attr_accessor :customer_address

    # Customer's country of residence. Used for compliance and tax reporting.
    attr_accessor :customer_country

    # Customer's country ISO 3166-1 alpha-2 code. Used for automated compliance checks.
    attr_accessor :customer_country_iso

    # Customer's state or province. Required for US and Canadian customers.
    attr_accessor :customer_province

    # Customer's state or province ISO code. Used for automated tax calculations.
    attr_accessor :customer_province_iso

    # Customer's phone number with country code. Used for SMS notifications and verification.
    attr_accessor :phone_number

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'source_currency' => :'sourceCurrency',
        :'source_network' => :'sourceNetwork',
        :'destination_currency' => :'destinationCurrency',
        :'destination_network' => :'destinationNetwork',
        :'destination_address' => :'destinationAddress',
        :'amount' => :'amount',
        :'customer_first_name' => :'customer_first_name',
        :'customer_last_name' => :'customer_last_name',
        :'customer_email' => :'customer_email',
        :'customer_address' => :'customer_address',
        :'customer_country' => :'customer_country',
        :'customer_country_iso' => :'customer_countryISO',
        :'customer_province' => :'customer_province',
        :'customer_province_iso' => :'customer_provinceISO',
        :'phone_number' => :'phoneNumber'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'source_currency' => :'StableCoinCurrency',
        :'source_network' => :'BridgePaymentRail',
        :'destination_currency' => :'StableCoinCurrency',
        :'destination_network' => :'BridgePaymentRail',
        :'destination_address' => :'String',
        :'amount' => :'String',
        :'customer_first_name' => :'String',
        :'customer_last_name' => :'String',
        :'customer_email' => :'String',
        :'customer_address' => :'String',
        :'customer_country' => :'String',
        :'customer_country_iso' => :'String',
        :'customer_province' => :'String',
        :'customer_province_iso' => :'String',
        :'phone_number' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Devdraft::CreateStablePaymentIntentDto` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Devdraft::CreateStablePaymentIntentDto`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'source_currency')
        self.source_currency = attributes[:'source_currency']
      else
        self.source_currency = nil
      end

      if attributes.key?(:'source_network')
        self.source_network = attributes[:'source_network']
      else
        self.source_network = nil
      end

      if attributes.key?(:'destination_currency')
        self.destination_currency = attributes[:'destination_currency']
      end

      if attributes.key?(:'destination_network')
        self.destination_network = attributes[:'destination_network']
      else
        self.destination_network = nil
      end

      if attributes.key?(:'destination_address')
        self.destination_address = attributes[:'destination_address']
      end

      if attributes.key?(:'amount')
        self.amount = attributes[:'amount']
      end

      if attributes.key?(:'customer_first_name')
        self.customer_first_name = attributes[:'customer_first_name']
      end

      if attributes.key?(:'customer_last_name')
        self.customer_last_name = attributes[:'customer_last_name']
      end

      if attributes.key?(:'customer_email')
        self.customer_email = attributes[:'customer_email']
      end

      if attributes.key?(:'customer_address')
        self.customer_address = attributes[:'customer_address']
      end

      if attributes.key?(:'customer_country')
        self.customer_country = attributes[:'customer_country']
      end

      if attributes.key?(:'customer_country_iso')
        self.customer_country_iso = attributes[:'customer_country_iso']
      end

      if attributes.key?(:'customer_province')
        self.customer_province = attributes[:'customer_province']
      end

      if attributes.key?(:'customer_province_iso')
        self.customer_province_iso = attributes[:'customer_province_iso']
      end

      if attributes.key?(:'phone_number')
        self.phone_number = attributes[:'phone_number']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @source_currency.nil?
        invalid_properties.push('invalid value for "source_currency", source_currency cannot be nil.')
      end

      if @source_network.nil?
        invalid_properties.push('invalid value for "source_network", source_network cannot be nil.')
      end

      if @destination_network.nil?
        invalid_properties.push('invalid value for "destination_network", destination_network cannot be nil.')
      end

      pattern = Regexp.new(/^\d+(\.\d{1,6})?$/)
      if !@amount.nil? && @amount !~ pattern
        invalid_properties.push("invalid value for \"amount\", must conform to the pattern #{pattern}.")
      end

      if !@customer_first_name.nil? && @customer_first_name.to_s.length > 100
        invalid_properties.push('invalid value for "customer_first_name", the character length must be smaller than or equal to 100.')
      end

      if !@customer_last_name.nil? && @customer_last_name.to_s.length > 100
        invalid_properties.push('invalid value for "customer_last_name", the character length must be smaller than or equal to 100.')
      end

      if !@customer_email.nil? && @customer_email.to_s.length > 255
        invalid_properties.push('invalid value for "customer_email", the character length must be smaller than or equal to 255.')
      end

      if !@customer_address.nil? && @customer_address.to_s.length > 500
        invalid_properties.push('invalid value for "customer_address", the character length must be smaller than or equal to 500.')
      end

      if !@customer_country.nil? && @customer_country.to_s.length > 100
        invalid_properties.push('invalid value for "customer_country", the character length must be smaller than or equal to 100.')
      end

      if !@customer_country_iso.nil? && @customer_country_iso.to_s.length > 2
        invalid_properties.push('invalid value for "customer_country_iso", the character length must be smaller than or equal to 2.')
      end

      pattern = Regexp.new(/^[A-Z]{2}$/)
      if !@customer_country_iso.nil? && @customer_country_iso !~ pattern
        invalid_properties.push("invalid value for \"customer_country_iso\", must conform to the pattern #{pattern}.")
      end

      if !@customer_province.nil? && @customer_province.to_s.length > 100
        invalid_properties.push('invalid value for "customer_province", the character length must be smaller than or equal to 100.')
      end

      if !@customer_province_iso.nil? && @customer_province_iso.to_s.length > 10
        invalid_properties.push('invalid value for "customer_province_iso", the character length must be smaller than or equal to 10.')
      end

      if !@phone_number.nil? && @phone_number.to_s.length > 20
        invalid_properties.push('invalid value for "phone_number", the character length must be smaller than or equal to 20.')
      end

      pattern = Regexp.new(/^[+]?[\d\s\-\(\)]+$/)
      if !@phone_number.nil? && @phone_number !~ pattern
        invalid_properties.push("invalid value for \"phone_number\", must conform to the pattern #{pattern}.")
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @source_currency.nil?
      return false if @source_network.nil?
      return false if @destination_network.nil?
      return false if !@amount.nil? && @amount !~ Regexp.new(/^\d+(\.\d{1,6})?$/)
      return false if !@customer_first_name.nil? && @customer_first_name.to_s.length > 100
      return false if !@customer_last_name.nil? && @customer_last_name.to_s.length > 100
      return false if !@customer_email.nil? && @customer_email.to_s.length > 255
      return false if !@customer_address.nil? && @customer_address.to_s.length > 500
      return false if !@customer_country.nil? && @customer_country.to_s.length > 100
      return false if !@customer_country_iso.nil? && @customer_country_iso.to_s.length > 2
      return false if !@customer_country_iso.nil? && @customer_country_iso !~ Regexp.new(/^[A-Z]{2}$/)
      return false if !@customer_province.nil? && @customer_province.to_s.length > 100
      return false if !@customer_province_iso.nil? && @customer_province_iso.to_s.length > 10
      return false if !@phone_number.nil? && @phone_number.to_s.length > 20
      return false if !@phone_number.nil? && @phone_number !~ Regexp.new(/^[+]?[\d\s\-\(\)]+$/)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] source_currency Value to be assigned
    def source_currency=(source_currency)
      if source_currency.nil?
        fail ArgumentError, 'source_currency cannot be nil'
      end

      @source_currency = source_currency
    end

    # Custom attribute writer method with validation
    # @param [Object] source_network Value to be assigned
    def source_network=(source_network)
      if source_network.nil?
        fail ArgumentError, 'source_network cannot be nil'
      end

      @source_network = source_network
    end

    # Custom attribute writer method with validation
    # @param [Object] destination_network Value to be assigned
    def destination_network=(destination_network)
      if destination_network.nil?
        fail ArgumentError, 'destination_network cannot be nil'
      end

      @destination_network = destination_network
    end

    # Custom attribute writer method with validation
    # @param [Object] amount Value to be assigned
    def amount=(amount)
      if amount.nil?
        fail ArgumentError, 'amount cannot be nil'
      end

      pattern = Regexp.new(/^\d+(\.\d{1,6})?$/)
      if amount !~ pattern
        fail ArgumentError, "invalid value for \"amount\", must conform to the pattern #{pattern}."
      end

      @amount = amount
    end

    # Custom attribute writer method with validation
    # @param [Object] customer_first_name Value to be assigned
    def customer_first_name=(customer_first_name)
      if customer_first_name.nil?
        fail ArgumentError, 'customer_first_name cannot be nil'
      end

      if customer_first_name.to_s.length > 100
        fail ArgumentError, 'invalid value for "customer_first_name", the character length must be smaller than or equal to 100.'
      end

      @customer_first_name = customer_first_name
    end

    # Custom attribute writer method with validation
    # @param [Object] customer_last_name Value to be assigned
    def customer_last_name=(customer_last_name)
      if customer_last_name.nil?
        fail ArgumentError, 'customer_last_name cannot be nil'
      end

      if customer_last_name.to_s.length > 100
        fail ArgumentError, 'invalid value for "customer_last_name", the character length must be smaller than or equal to 100.'
      end

      @customer_last_name = customer_last_name
    end

    # Custom attribute writer method with validation
    # @param [Object] customer_email Value to be assigned
    def customer_email=(customer_email)
      if customer_email.nil?
        fail ArgumentError, 'customer_email cannot be nil'
      end

      if customer_email.to_s.length > 255
        fail ArgumentError, 'invalid value for "customer_email", the character length must be smaller than or equal to 255.'
      end

      @customer_email = customer_email
    end

    # Custom attribute writer method with validation
    # @param [Object] customer_address Value to be assigned
    def customer_address=(customer_address)
      if customer_address.nil?
        fail ArgumentError, 'customer_address cannot be nil'
      end

      if customer_address.to_s.length > 500
        fail ArgumentError, 'invalid value for "customer_address", the character length must be smaller than or equal to 500.'
      end

      @customer_address = customer_address
    end

    # Custom attribute writer method with validation
    # @param [Object] customer_country Value to be assigned
    def customer_country=(customer_country)
      if customer_country.nil?
        fail ArgumentError, 'customer_country cannot be nil'
      end

      if customer_country.to_s.length > 100
        fail ArgumentError, 'invalid value for "customer_country", the character length must be smaller than or equal to 100.'
      end

      @customer_country = customer_country
    end

    # Custom attribute writer method with validation
    # @param [Object] customer_country_iso Value to be assigned
    def customer_country_iso=(customer_country_iso)
      if customer_country_iso.nil?
        fail ArgumentError, 'customer_country_iso cannot be nil'
      end

      if customer_country_iso.to_s.length > 2
        fail ArgumentError, 'invalid value for "customer_country_iso", the character length must be smaller than or equal to 2.'
      end

      pattern = Regexp.new(/^[A-Z]{2}$/)
      if customer_country_iso !~ pattern
        fail ArgumentError, "invalid value for \"customer_country_iso\", must conform to the pattern #{pattern}."
      end

      @customer_country_iso = customer_country_iso
    end

    # Custom attribute writer method with validation
    # @param [Object] customer_province Value to be assigned
    def customer_province=(customer_province)
      if customer_province.nil?
        fail ArgumentError, 'customer_province cannot be nil'
      end

      if customer_province.to_s.length > 100
        fail ArgumentError, 'invalid value for "customer_province", the character length must be smaller than or equal to 100.'
      end

      @customer_province = customer_province
    end

    # Custom attribute writer method with validation
    # @param [Object] customer_province_iso Value to be assigned
    def customer_province_iso=(customer_province_iso)
      if customer_province_iso.nil?
        fail ArgumentError, 'customer_province_iso cannot be nil'
      end

      if customer_province_iso.to_s.length > 10
        fail ArgumentError, 'invalid value for "customer_province_iso", the character length must be smaller than or equal to 10.'
      end

      @customer_province_iso = customer_province_iso
    end

    # Custom attribute writer method with validation
    # @param [Object] phone_number Value to be assigned
    def phone_number=(phone_number)
      if phone_number.nil?
        fail ArgumentError, 'phone_number cannot be nil'
      end

      if phone_number.to_s.length > 20
        fail ArgumentError, 'invalid value for "phone_number", the character length must be smaller than or equal to 20.'
      end

      pattern = Regexp.new(/^[+]?[\d\s\-\(\)]+$/)
      if phone_number !~ pattern
        fail ArgumentError, "invalid value for \"phone_number\", must conform to the pattern #{pattern}."
      end

      @phone_number = phone_number
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          source_currency == o.source_currency &&
          source_network == o.source_network &&
          destination_currency == o.destination_currency &&
          destination_network == o.destination_network &&
          destination_address == o.destination_address &&
          amount == o.amount &&
          customer_first_name == o.customer_first_name &&
          customer_last_name == o.customer_last_name &&
          customer_email == o.customer_email &&
          customer_address == o.customer_address &&
          customer_country == o.customer_country &&
          customer_country_iso == o.customer_country_iso &&
          customer_province == o.customer_province &&
          customer_province_iso == o.customer_province_iso &&
          phone_number == o.phone_number
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [source_currency, source_network, destination_currency, destination_network, destination_address, amount, customer_first_name, customer_last_name, customer_email, customer_address, customer_country, customer_country_iso, customer_province, customer_province_iso, phone_number].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
