=begin
#Devdraft AI Payment & Business Management API

# A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.17.0

=end

require 'date'
require 'time'

module Devdraft
  class CreateBankPaymentIntentDto < ApiModelBase
    # The banking payment method to use for the transfer. Determines processing time and fees.
    attr_accessor :source_payment_rail

    # The fiat currency to convert FROM. Must match the currency of the source payment rail.
    attr_accessor :source_currency

    # The stablecoin currency to convert TO. The customer will receive this currency.
    attr_accessor :destination_currency

    # The blockchain network where the stablecoin will be delivered. Must support the destination currency.
    attr_accessor :destination_network

    # Destination wallet address. Supports Ethereum (0x...) and Solana address formats.
    attr_accessor :destination_address

    # Payment amount (optional for flexible amount)
    attr_accessor :amount

    # Customer first name
    attr_accessor :customer_first_name

    # Customer last name
    attr_accessor :customer_last_name

    # Customer email address
    attr_accessor :customer_email

    # Customer address
    attr_accessor :customer_address

    # Customer country
    attr_accessor :customer_country

    # Customer country ISO code
    attr_accessor :customer_country_iso

    # Customer province/state
    attr_accessor :customer_province

    # Customer province/state ISO code
    attr_accessor :customer_province_iso

    # Customer phone number
    attr_accessor :phone_number

    # Wire transfer message (for WIRE transfers)
    attr_accessor :wire_message

    # SEPA reference (for SEPA transfers)
    attr_accessor :sepa_reference

    # ACH reference (for ACH transfers)
    attr_accessor :ach_reference

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'source_payment_rail' => :'sourcePaymentRail',
        :'source_currency' => :'sourceCurrency',
        :'destination_currency' => :'destinationCurrency',
        :'destination_network' => :'destinationNetwork',
        :'destination_address' => :'destinationAddress',
        :'amount' => :'amount',
        :'customer_first_name' => :'customer_first_name',
        :'customer_last_name' => :'customer_last_name',
        :'customer_email' => :'customer_email',
        :'customer_address' => :'customer_address',
        :'customer_country' => :'customer_country',
        :'customer_country_iso' => :'customer_countryISO',
        :'customer_province' => :'customer_province',
        :'customer_province_iso' => :'customer_provinceISO',
        :'phone_number' => :'phoneNumber',
        :'wire_message' => :'wire_message',
        :'sepa_reference' => :'sepa_reference',
        :'ach_reference' => :'ach_reference'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'source_payment_rail' => :'BridgePaymentRail',
        :'source_currency' => :'FiatCurrency',
        :'destination_currency' => :'StableCoinCurrency',
        :'destination_network' => :'BridgePaymentRail',
        :'destination_address' => :'String',
        :'amount' => :'String',
        :'customer_first_name' => :'String',
        :'customer_last_name' => :'String',
        :'customer_email' => :'String',
        :'customer_address' => :'String',
        :'customer_country' => :'String',
        :'customer_country_iso' => :'String',
        :'customer_province' => :'String',
        :'customer_province_iso' => :'String',
        :'phone_number' => :'String',
        :'wire_message' => :'String',
        :'sepa_reference' => :'String',
        :'ach_reference' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Devdraft::CreateBankPaymentIntentDto` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Devdraft::CreateBankPaymentIntentDto`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'source_payment_rail')
        self.source_payment_rail = attributes[:'source_payment_rail']
      else
        self.source_payment_rail = nil
      end

      if attributes.key?(:'source_currency')
        self.source_currency = attributes[:'source_currency']
      else
        self.source_currency = nil
      end

      if attributes.key?(:'destination_currency')
        self.destination_currency = attributes[:'destination_currency']
      else
        self.destination_currency = nil
      end

      if attributes.key?(:'destination_network')
        self.destination_network = attributes[:'destination_network']
      else
        self.destination_network = nil
      end

      if attributes.key?(:'destination_address')
        self.destination_address = attributes[:'destination_address']
      end

      if attributes.key?(:'amount')
        self.amount = attributes[:'amount']
      end

      if attributes.key?(:'customer_first_name')
        self.customer_first_name = attributes[:'customer_first_name']
      end

      if attributes.key?(:'customer_last_name')
        self.customer_last_name = attributes[:'customer_last_name']
      end

      if attributes.key?(:'customer_email')
        self.customer_email = attributes[:'customer_email']
      end

      if attributes.key?(:'customer_address')
        self.customer_address = attributes[:'customer_address']
      end

      if attributes.key?(:'customer_country')
        self.customer_country = attributes[:'customer_country']
      end

      if attributes.key?(:'customer_country_iso')
        self.customer_country_iso = attributes[:'customer_country_iso']
      end

      if attributes.key?(:'customer_province')
        self.customer_province = attributes[:'customer_province']
      end

      if attributes.key?(:'customer_province_iso')
        self.customer_province_iso = attributes[:'customer_province_iso']
      end

      if attributes.key?(:'phone_number')
        self.phone_number = attributes[:'phone_number']
      end

      if attributes.key?(:'wire_message')
        self.wire_message = attributes[:'wire_message']
      end

      if attributes.key?(:'sepa_reference')
        self.sepa_reference = attributes[:'sepa_reference']
      end

      if attributes.key?(:'ach_reference')
        self.ach_reference = attributes[:'ach_reference']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @source_payment_rail.nil?
        invalid_properties.push('invalid value for "source_payment_rail", source_payment_rail cannot be nil.')
      end

      if @source_currency.nil?
        invalid_properties.push('invalid value for "source_currency", source_currency cannot be nil.')
      end

      if @destination_currency.nil?
        invalid_properties.push('invalid value for "destination_currency", destination_currency cannot be nil.')
      end

      if @destination_network.nil?
        invalid_properties.push('invalid value for "destination_network", destination_network cannot be nil.')
      end

      if !@wire_message.nil? && @wire_message.to_s.length > 256
        invalid_properties.push('invalid value for "wire_message", the character length must be smaller than or equal to 256.')
      end

      if !@sepa_reference.nil? && @sepa_reference.to_s.length > 140
        invalid_properties.push('invalid value for "sepa_reference", the character length must be smaller than or equal to 140.')
      end

      if !@sepa_reference.nil? && @sepa_reference.to_s.length < 6
        invalid_properties.push('invalid value for "sepa_reference", the character length must be greater than or equal to 6.')
      end

      if !@ach_reference.nil? && @ach_reference.to_s.length > 10
        invalid_properties.push('invalid value for "ach_reference", the character length must be smaller than or equal to 10.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @source_payment_rail.nil?
      return false if @source_currency.nil?
      return false if @destination_currency.nil?
      return false if @destination_network.nil?
      return false if !@wire_message.nil? && @wire_message.to_s.length > 256
      return false if !@sepa_reference.nil? && @sepa_reference.to_s.length > 140
      return false if !@sepa_reference.nil? && @sepa_reference.to_s.length < 6
      return false if !@ach_reference.nil? && @ach_reference.to_s.length > 10
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] source_payment_rail Value to be assigned
    def source_payment_rail=(source_payment_rail)
      if source_payment_rail.nil?
        fail ArgumentError, 'source_payment_rail cannot be nil'
      end

      @source_payment_rail = source_payment_rail
    end

    # Custom attribute writer method with validation
    # @param [Object] source_currency Value to be assigned
    def source_currency=(source_currency)
      if source_currency.nil?
        fail ArgumentError, 'source_currency cannot be nil'
      end

      @source_currency = source_currency
    end

    # Custom attribute writer method with validation
    # @param [Object] destination_currency Value to be assigned
    def destination_currency=(destination_currency)
      if destination_currency.nil?
        fail ArgumentError, 'destination_currency cannot be nil'
      end

      @destination_currency = destination_currency
    end

    # Custom attribute writer method with validation
    # @param [Object] destination_network Value to be assigned
    def destination_network=(destination_network)
      if destination_network.nil?
        fail ArgumentError, 'destination_network cannot be nil'
      end

      @destination_network = destination_network
    end

    # Custom attribute writer method with validation
    # @param [Object] wire_message Value to be assigned
    def wire_message=(wire_message)
      if wire_message.nil?
        fail ArgumentError, 'wire_message cannot be nil'
      end

      if wire_message.to_s.length > 256
        fail ArgumentError, 'invalid value for "wire_message", the character length must be smaller than or equal to 256.'
      end

      @wire_message = wire_message
    end

    # Custom attribute writer method with validation
    # @param [Object] sepa_reference Value to be assigned
    def sepa_reference=(sepa_reference)
      if sepa_reference.nil?
        fail ArgumentError, 'sepa_reference cannot be nil'
      end

      if sepa_reference.to_s.length > 140
        fail ArgumentError, 'invalid value for "sepa_reference", the character length must be smaller than or equal to 140.'
      end

      if sepa_reference.to_s.length < 6
        fail ArgumentError, 'invalid value for "sepa_reference", the character length must be greater than or equal to 6.'
      end

      @sepa_reference = sepa_reference
    end

    # Custom attribute writer method with validation
    # @param [Object] ach_reference Value to be assigned
    def ach_reference=(ach_reference)
      if ach_reference.nil?
        fail ArgumentError, 'ach_reference cannot be nil'
      end

      if ach_reference.to_s.length > 10
        fail ArgumentError, 'invalid value for "ach_reference", the character length must be smaller than or equal to 10.'
      end

      @ach_reference = ach_reference
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          source_payment_rail == o.source_payment_rail &&
          source_currency == o.source_currency &&
          destination_currency == o.destination_currency &&
          destination_network == o.destination_network &&
          destination_address == o.destination_address &&
          amount == o.amount &&
          customer_first_name == o.customer_first_name &&
          customer_last_name == o.customer_last_name &&
          customer_email == o.customer_email &&
          customer_address == o.customer_address &&
          customer_country == o.customer_country &&
          customer_country_iso == o.customer_country_iso &&
          customer_province == o.customer_province &&
          customer_province_iso == o.customer_province_iso &&
          phone_number == o.phone_number &&
          wire_message == o.wire_message &&
          sepa_reference == o.sepa_reference &&
          ach_reference == o.ach_reference
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [source_payment_rail, source_currency, destination_currency, destination_network, destination_address, amount, customer_first_name, customer_last_name, customer_email, customer_address, customer_country, customer_country_iso, customer_province, customer_province_iso, phone_number, wire_message, sepa_reference, ach_reference].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
