=begin
#Devdraft AI Payment & Business Management API

# A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.17.0

=end

require 'date'
require 'time'

module Devdraft
  class CustomerType
    INDIVIDUAL = "Individual".freeze
    STARTUP = "Startup".freeze
    SMALL_BUSINESS = "Small Business".freeze
    MEDIUM_BUSINESS = "Medium Business".freeze
    ENTERPRISE = "Enterprise".freeze
    NON_PROFIT = "Non-Profit".freeze
    GOVERNMENT = "Government".freeze

    def self.all_vars
      @all_vars ||= [INDIVIDUAL, STARTUP, SMALL_BUSINESS, MEDIUM_BUSINESS, ENTERPRISE, NON_PROFIT, GOVERNMENT].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if CustomerType.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #CustomerType"
    end
  end
end
