=begin
#Devdraft AI Payment & Business Management API

# A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.17.0

=end

require 'date'
require 'time'

module Devdraft
  class DestinationCurrency
    USD = "usd".freeze
    EUR = "eur".freeze
    MXN = "mxn".freeze
    USDC = "usdc".freeze
    EURC = "eurc".freeze
    DAI = "dai".freeze
    PYUSD = "pyusd".freeze
    USDT = "usdt".freeze

    def self.all_vars
      @all_vars ||= [USD, EUR, MXN, USDC, EURC, DAI, PYUSD, USDT].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if DestinationCurrency.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #DestinationCurrency"
    end
  end
end
